project_id = "tumanpeywddnixgyfale"

[functions.send-transactional-email]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.manage-coupons]
verify_jwt = true

[functions.process-withdrawal]
verify_jwt = true

[functions.admin-approve-withdrawal]
verify_jwt = true

[functions.admin-manual-adjustment]
verify_jwt = true
